// Catálogo de telas da vertical To Do Green — dado puro, sem React.
//
// `MODULE_IMPLEMENTATION` dá título, rótulo curto do menu, rota, área e
// permissão de cada tela; `IMPLEMENTED_MODULE_IDS` diz quais nomes do catálogo
// de rotinas já abrem uma tela pronta. Menu, trilha, permissão da rota e o
// despacho das telas leem daqui.

export const IMPLEMENTED_MODULE_IDS = new Set([
  "dashboard",
  "painel-comercial",
  "conectores",
  "dashboard-esg",
  "central-esg",
  "relatorios-esg",
  "metodologia",
  "cofre-evidencias",
  "clientes",
  "contatos",
  "oportunidades",
  "funil",
  "estudio-criativo",
  "midia",
  "editor-codigo",
  "analise-texto",
  "mapa-ideias",
  "pipeline",
  "propostas",
  "contratos",
  "simulacoes",
  "precificacao",
  "deal-desk",
  "implantacao",
  "produtos",
  "catalogo-produtos",
  "planejamento",
  "aceite-viagens",
  "ciot",
  "receita",
  "forecast",
  "faturamento",
  "recebimento",
  "custos",
  "opex",
  "margem",
  "rentabilidade",
  "operacoes",
  "produtos-logisticos",
  "rotas",
  "roteirizacao",
  "pontos-recarga",
  "sessoes-recarga",
  "reservas-recarga",
  "cobranca-recarga",
  "viagens",
  "veiculos",
  "motorista-frota",
  "entregas",
  "ocupacao",
  "produtividade",
  "energia",
  "ocorrencias",
  "relatorios",
  "auditoria",
  "usuarios",
  "permissoes",
  "configuracoes",
  "dashboards",
  "metas",
  "performance-comercial",
  "playbook-comercial",
  "solicitacoes",
  "estoque",
  "compras",
  "cadastros",
  "dp-rh",
  "motoristas",
  "escalas",
  "qualidade",
  "marketing",
  "campanhas",
  "comunicacao-interna",
  "juridico",
  "indicadores",
  "administracao",
  "fiscal",
  "tesouraria",
  "greenpay",
  "cte",
  "mdfe",
  "nfse",
  "planner",
  "rasci",
  "fluxos",
  "manual",
  "comissoes",
  "espaco",
  "visualizacoes",
  "agentes-funcoes",
  // CAT-01: Sincronizar 13 módulos que faltavam em IMPLEMENTED
  "remuneracao",
  "benchmark",
  "central-rfq",
  "sobre-o-negocio",
  "orcamento",
  "centros-custo",
  "pacotes",
  "tarefas",
  "avancos",
  "documentos",
  "aprovacoes",
  "notificacoes",
  "inbox",
  "saude-sistema",
  // CAT-01 (2ª leva): módulos com página renderizada e entrada em
  // MODULE_IMPLEMENTATION que apareciam como "Em implantação" por faltarem
  // aqui. A área Green Tech Core inteira estava escondida do menu. O teste
  // src/logistics-module-catalog.test.js barra essa divergência daqui pra
  // frente (toda chave de MODULE_IMPLEMENTATION tem de estar neste conjunto).
  "motor-operacao",
  "ordens-servico",
  "core-grupo",
  "tenant-acessos",
  "green-on-empresa",
  "roaming-ocpi",
  "energia-peak",
  "fila-alertas",
  "greenmob-locacao",
  "saas-billing",
  "ocpp-console",
  "green-on-app",
  "seguranca-fisica",
]);

export const MODULE_IMPLEMENTATION = Object.freeze({
  dashboard: {
    title: "Principal",
    navLabel: "Principal",
    route: "/todogreen/dashboard",
    area: "principal",
    status: "functional",
    description: "Indicadores, pendências e atalhos do ERP.",
  },
  dashboards: {
    title: "Painéis personalizados",
    navLabel: "Meus painéis",
    route: "/todogreen/dashboards",
    area: "indicadores",
    status: "functional",
    description: "Monte painéis com os indicadores que a sua equipe acompanha.",
  },
  espaco: {
    title: "Espaço de trabalho",
    navLabel: "Visão geral",
    route: "/todogreen/espaco",
    area: "espaco-trabalho",
    status: "functional",
    description: "Projetos, tarefas, conhecimento, visualizações e agentes no mesmo espaço de trabalho.",
  },
  visualizacoes: {
    title: "Visualizações do trabalho",
    navLabel: "Visualizações e gráficos",
    route: "/todogreen/visualizacoes",
    area: "espaco-trabalho",
    status: "functional",
    description: "Lista, Gantt, timeline, calendário, workload e gráficos alimentados pela mesma base de projetos e tarefas.",
  },
  "agentes-funcoes": {
    title: "Agentes e funções",
    navLabel: "Agentes e funções",
    route: "/todogreen/agentes",
    area: "espaco-trabalho",
    status: "functional",
    description: "Agentes herdados do Seu Funcionário, suas funções, execuções e aprovações.",
  },
  avancos: {
    title: "Avanços da semana",
    navLabel: "Avanços da semana",
    route: "/todogreen/avancos",
    area: "espaco-trabalho",
    status: "functional",
    permission: ["crm:manage", "clients:manage", "audit:read"],
    description: "As oportunidades com movimento concreto nos últimos sete dias, com o avanço escrito por quem trabalhou nelas.",
  },
  metas: {
    title: "Metas e acompanhamento",
    navLabel: "Metas",
    route: "/todogreen/metas",
    area: "comercial",
    status: "functional",
    permission: "goal:read",
    description: "Metas com medição, check-ins e planos de ação.",
  },
  "performance-comercial": {
    title: "Performance comercial",
    navLabel: "Performance",
    route: "/todogreen/performance-comercial",
    area: "comercial",
    status: "functional",
    permission: ["crm:manage", "clients:manage"],
    description: "Execução da carteira e atingimento de metas, sem misturar oportunidades, pipeline ou faturamento.",
  },
  "playbook-comercial": {
    title: "Playbook comercial",
    navLabel: "Playbook",
    route: "/todogreen/playbook-comercial",
    area: "comercial",
    status: "functional",
    description: "Jornada de venda, critérios de avanço e atalhos comerciais.",
  },
  "painel-comercial": {
    title: "Painel comercial",
    navLabel: "Painel comercial",
    route: "/todogreen/painel-comercial",
    area: "comercial",
    status: "functional",
    permission: ["crm:manage", "clients:manage", "revenue:manage", "finance:manage", "audit:read"],
    description: "Receita novos negócios, kanban de clientes e modelo operacional em uma tela, com dados reais das fontes conectadas.",
  },
  clientes: {
    title: "Clientes",
    navLabel: "Clientes",
    route: "/todogreen/clientes",
    area: "comercial",
    status: "functional",
    permission: ["crm:manage", "clients:manage", "clients:read"],
    description: "Centralize dados comerciais, contatos e próximos passos de cada conta.",
  },
  oportunidades: {
    title: "Oportunidades e pipeline",
    navLabel: "Oportunidades",
    route: "/todogreen/oportunidades",
    area: "comercial",
    status: "functional",
    permission: "crm:manage",
    description: "Acompanhe cada negociação por etapa, valor e chance de fechar.",
  },
  funil: {
    title: "Funil de vendas",
    navLabel: "Funil de vendas",
    route: "/todogreen/funil",
    area: "comercial",
    status: "functional",
    permission: "crm:manage",
    description: "Previsão ponderada do comercial: valor por etapa, taxa de fechamento, ticket e ciclo médios e forecast dos próximos meses.",
  },
  "estudio-criativo": {
    title: "Estúdio criativo",
    navLabel: "Estúdio criativo",
    route: "/todogreen/estudio-criativo",
    area: "estudio",
    status: "functional",
    permission: "marketing:manage",
    description: "Gera logos e imagens com a IA disponível, com o contexto da To Do Green.",
  },
  midia: {
    title: "Mídia",
    navLabel: "Mídia",
    route: "/todogreen/midia",
    area: "estudio",
    status: "functional",
    permission: "marketing:manage",
    description: "Edita foto, grava recado em áudio e guarda na biblioteca — tudo no aparelho, sem enviar arquivo para fora.",
  },
  "editor-codigo": {
    title: "Editor de código",
    navLabel: "Editor de código",
    route: "/todogreen/editor-codigo",
    area: "estudio",
    status: "functional",
    permission: "marketing:manage",
    description: "Monta uma página, formulário ou cartão em HTML/CSS/JS e vê o resultado na hora, com download pronto para publicar.",
  },
  "analise-texto": {
    title: "Análise de textos",
    navLabel: "Análise de textos",
    route: "/todogreen/analise-texto",
    area: "estudio",
    status: "functional",
    permission: "marketing:manage",
    description: "Cola um contrato, edital ou proposta (ou envia PDF/DOCX) e a IA resume, aponta riscos e responde perguntas — só com o que está no texto.",
  },
  "mapa-ideias": {
    title: "Mapa de ideias",
    navLabel: "Mapa de ideias",
    route: "/todogreen/mapa-ideias",
    area: "estudio",
    status: "functional",
    permission: "marketing:manage",
    description: "Descreve um tema (rota nova, cliente, campanha) e a IA abre em ramos e ideias acionáveis, que viram tarefas.",
  },
  propostas: {
    title: "Propostas e contratos",
    navLabel: "Propostas",
    route: "/todogreen/propostas",
    area: "comercial",
    status: "functional",
    permission: ["proposal:create", "proposal:manage", "deal:review", "deal:approve"],
    description: "Geração de proposta textual com preço, premissas, ROI ambiental, ressalvas e aprovações necessárias.",
  },
  precificacao: {
    title: "Precificação e aprovação comercial",
    navLabel: "Precificação",
    route: "/todogreen/precificacao",
    area: "comercial",
    status: "functional",
    permission: ["pricing:simulate", "pricing:manage"],
    description: "Calculadoras por produto, margem, custo, target, gatilhos de aprovação e evidências obrigatórias.",
  },
  implantacao: {
    title: "Implantação de cliente",
    navLabel: "Implantação",
    route: "/todogreen/implantacao",
    area: "implantacao",
    status: "functional",
    permission: ["clients:manage", "clients:read", "operations:manage", "planning:manage"],
    description: "Go-live do cliente: contrato, operação, SLA e portal.",
  },
  produtos: {
    title: "Produtos logísticos",
    navLabel: "Catálogo",
    route: "/todogreen/produtos",
    area: "produtos",
    status: "functional",
    permission: "product:manage",
    description: "Catálogo de first, middle e last mile com escopo, SLA, unidade de cobrança, premissas e restrições por produto.",
  },
  "motor-operacao": {
    title: "Motor de HC e DRE",
    navLabel: "Motor HC e DRE",
    route: "/todogreen/motor-operacao",
    area: "produtos",
    status: "functional",
    description: "Régua editável por admin (impostos, margem, headcount) e simulador de dimensionamento e resultado por tipo de operação.",
  },
  planejamento: {
    title: "Planejamento operacional",
    navLabel: "Liberação de OS",
    route: "/todogreen/planejamento",
    area: "operacao",
    status: "functional",
    permission: ["planning:manage", "operations:manage"],
    description: "Decide aceite de viagem ou OS com capacidade, produto, SLA, risco, margem e janela operacional.",
  },
  "aceite-viagens": {
    title: "Aceito esta viagem?",
    navLabel: "Aceito esta viagem?",
    route: "/todogreen/aceite-viagens",
    area: "operacao",
    status: "functional",
    permission: ["planning:manage", "operations:manage"],
    description: "Simulador de aceite: custos obrigatórios, margem calculada e decisão registrada antes de virar OS.",
  },
  ciot: {
    title: "CIOT",
    navLabel: "CIOT",
    route: "/todogreen/ciot",
    area: "operacao",
    status: "functional",
    permission: "ciot:manage",
    description: "Emissão de CIOT com piso mínimo e protocolo.",
  },
  ocorrencias: {
    title: "Ocorrências e exceções operacionais",
    navLabel: "Ocorrências",
    route: "/todogreen/ocorrencias",
    area: "operacao",
    status: "functional",
    permission: ["operations:manage", "tms:manage", "evidence:manage"],
    description: "Atrasos, insucessos, reentregas e eventos críticos ligados à operação.",
  },
  comissoes: {
    title: "Comissões",
    navLabel: "Comissões",
    route: "/todogreen/comissoes",
    area: "financeiro",
    status: "functional",
    permission: ["commission:manage", "finance:manage", "audit:read"],
    description: "Comissão por lançamento, com baixa e estorno pelo mesmo razão.",
  },
  rasci: {
    title: "Matriz RASCI",
    navLabel: "RASCI",
    route: "/todogreen/rasci",
    area: "administracao",
    status: "functional",
    description: "Quem executa, aprova, apoia, consulta e é informado em cada área — numa aba só.",
  },
  fluxos: {
    title: "Fluxos entre áreas",
    navLabel: "Fluxos",
    route: "/todogreen/fluxos",
    area: "administracao",
    status: "functional",
    description: "Como o trabalho passa de uma área para a outra, do produto ao caixa — numa aba só.",
  },
  manual: {
    title: "Manual do ERP",
    navLabel: "Manual",
    route: "/todogreen/manual",
    area: "administracao",
    status: "functional",
    description: "O que cada módulo faz e a permissão que exige; gerado do catálogo, sempre atual.",
  },
  esg: {
    title: "ESG, Green Score e emissões da cadeia logística",
    navLabel: "ESG operacional",
    route: "/todogreen/esg",
    area: "esg",
    status: "functional",
    permission: ["esg:manage", "audit:read", "deal:review"],
    description: "CO2 evitado, diesel não consumido, equivalências, metodologia e textos comerciais auditáveis.",
  },
  regua: {
    title: "Parâmetros de preço",
    navLabel: "Parâmetros de preço",
    route: "/todogreen/parametros-simulador",
    area: "commercial",
    status: "functional",
    permission: "pricing:manage",
    description: "Custo de veículo, motorista, energia e margem que a precificação usa — com versão e fonte.",
  },
  "central-esg": {
    title: "Central ESG",
    navLabel: "Central ESG",
    route: "/todogreen/central-esg",
    area: "esg",
    status: "functional",
    permission: ["esg:manage", "audit:read", "deal:review"],
    description: "Calcula e grava o impacto com memória de cálculo, apura o Green Score com a régua em vigor e guarda a explicação de cada variação.",
  },
  energia: {
    title: "Gestão de Energia",
    navLabel: "Energia",
    route: "/todogreen/energia",
    area: "esg",
    status: "functional",
    permission: ["esg:manage", "fleet:manage", "audit:read"],
    description: "Consumo estimado, custo e emissões da frota cruzados com a capacidade da rede de recarga própria.",
  },
  solicitacoes: {
    title: "Solicitações de clientes",
    navLabel: "Solicitações",
    route: "/todogreen/solicitacoes",
    area: "implantacao",
    status: "functional",
    permission: ["clients:manage", "crm:manage", "operations:manage"],
    description: "Entrada do cliente antes do aceite, com prazo, produto provável, responsável, conversa e histórico.",
  },
  operacoes: {
    title: "Fretes e execução operacional",
    navLabel: "Fretes",
    route: "/todogreen/operacoes",
    area: "operacao",
    status: "functional",
    permission: ["operations:manage", "planning:manage", "tms:manage"],
    description: "Ficha operacional do frete com OS, execução, rota, entregas, documentos, fiscal, financeiro, SLA e histórico.",
  },
  "ordens-servico": {
    title: "Fretes, OS e aceite",
    navLabel: "OS e aceite",
    route: "/todogreen/ordens-servico",
    area: "operacao",
    status: "functional",
    permission: ["operations:manage", "planning:manage"],
    description: "Planejamento e Produtos liberam o frete; Operação executa; Financeiro só entra quando há elegibilidade de faturamento.",
  },
  roteirizacao: {
    title: "Roteirização no mapa",
    navLabel: "Roteirização",
    route: "/todogreen/roteirizacao",
    area: "operacao",
    status: "functional",
    permission: ["operations:manage", "planning:manage", "tms:manage"],
    description: "Origem e destino no mapa do OpenStreetMap, com a rota rodoviária, distância e tempo — sem chave e sem custo.",
  },
  "pontos-recarga": {
    title: "Pontos de recarga próprios",
    navLabel: "Pontos de recarga",
    route: "/todogreen/pontos-recarga",
    area: "operacao",
    status: "functional",
    permission: ["operations:manage", "planning:manage", "tms:manage", "fleet:manage"],
    description: "Cadastro dos carregadores próprios (Ground, GreenOn, pátio próprio) que entram no mapa do roteirizador junto à rede pública.",
  },
  "sessoes-recarga": {
    title: "Sessões de recarga",
    navLabel: "Sessões de recarga",
    route: "/todogreen/sessoes-recarga",
    area: "operacao",
    status: "functional",
    permission: ["operations:manage", "planning:manage", "fleet:manage", "finance:manage"],
    description: "Recargas com energia medida por ponto, veículo e cliente. O consumo real alimenta energia e cobrança sem duplicar a fonte.",
  },
  "reservas-recarga": {
    title: "Reservas de carregador",
    navLabel: "Reservas de recarga",
    route: "/todogreen/reservas-recarga",
    area: "operacao",
    status: "functional",
    permission: ["operations:manage", "planning:manage", "fleet:manage"],
    description: "Agenda dos pontos de recarga por veículo, com conflito de horário barrado antes da viagem.",
  },
  "cobranca-recarga": {
    title: "Cobrança de recarga (kWh)",
    navLabel: "Cobrança de recarga",
    route: "/todogreen/cobranca-recarga",
    area: "financeiro",
    status: "functional",
    permission: ["finance:manage", "revenue:manage"],
    description: "Preço por kWh e faturamento por cliente derivados somente de sessões medidas.",
  },
  cadastros: {
    title: "Cadastros logísticos",
    navLabel: "Cadastros",
    route: "/todogreen/cadastros",
    area: "cadastros",
    status: "functional",
    permission: ["clients:manage", "crm:manage", "stock:manage", "purchase:manage", "finance:manage", "fleet:manage", "hr:manage", "operations:manage", "planning:manage"],
    description: "Clientes, motoristas, veículos, tabelas, rotas, materiais, depósitos, parceiros, centros de custo e plano de contas.",
  },
  estoque: {
    title: "Estoque",
    navLabel: "Estoque",
    route: "/todogreen/estoque",
    area: "suprimentos",
    status: "functional",
    permission: "stock:manage",
    description: "Saldos, entradas, saídas, transferências e contagens.",
  },
  compras: {
    title: "Suprimentos",
    navLabel: "Suprimentos",
    route: "/todogreen/compras",
    area: "suprimentos",
    status: "functional",
    permission: "purchase:manage",
    description: "Requisições, aprovações, pedidos e recebimentos.",
  },
  tesouraria: {
    title: "Tesouraria, conciliação e fechamento",
    navLabel: "Tesouraria",
    route: "/todogreen/tesouraria",
    area: "financeiro",
    status: "functional",
    permission: "finance:manage",
    description: "Extrato OFX, conciliação, saldo por conta, cobrança com aging e fechamento de competência.",
  },
  greenpay: {
    title: "GreenPay — carteira dos motoristas",
    navLabel: "GreenPay",
    route: "/todogreen/greenpay",
    area: "financeiro",
    status: "functional",
    permission: "finance:manage",
    description: "Régua de ganhos por entrega e por km, sincronização das entregas e aprovação/pagamento da carteira de cada motorista.",
  },
  fiscal: {
    title: "Fiscal — CT-e, MDF-e e NFS-e",
    navLabel: "Fiscal",
    route: "/todogreen/fiscal",
    area: "financeiro",
    status: "functional",
    permission: "fiscal:manage",
    description: "CT-e, MDF-e e NFS-e; SEFAZ aguarda certificado.",
  },
  receita: {
    title: "Receita, forecast e faturamento",
    navLabel: "Receita",
    route: "/todogreen/receita",
    area: "financeiro",
    status: "functional",
    permission: ["revenue:manage", "finance:manage", "audit:read"],
    description: "Entradas financeiras por cliente/produto, forecast, faturamento, recebimento e comissão prevista.",
  },
  faturamento: {
    title: "Faturamento, CT-e e recebíveis",
    navLabel: "Faturamento",
    route: "/todogreen/faturamento",
    area: "financeiro",
    status: "functional",
    permission: ["revenue:manage", "finance:manage", "fiscal:manage"],
    description: "Fila de OS concluída, conferência fiscal, CT-e/documento, fechamento, título a receber e rastreabilidade.",
  },
  titulos: {
    title: "Títulos e baixas",
    navLabel: "Títulos e baixas",
    route: "/todogreen/titulos",
    area: "financeiro",
    status: "functional",
    permission: ["finance:manage", "revenue:manage", "cost:manage"],
    description: "Contas a pagar e receber com competência, vencimento, saldo, parcelas e liquidações rastreáveis.",
  },
  rateios: {
    title: "Rateio de custos",
    navLabel: "Rateio de custos",
    route: "/todogreen/rateios",
    area: "financeiro",
    status: "functional",
    permission: ["finance:manage", "cost:manage"],
    description: "Distribuição integral do custo por OS, operação, cliente, contrato, veículo, fornecedor e centro de custo.",
  },
  custos: {
    title: "Custos, margem e rateios",
    navLabel: "Custo e margem",
    route: "/todogreen/custos",
    area: "financeiro",
    status: "functional",
    permission: ["cost:manage", "finance:manage", "audit:read"],
    description: "Centro de custos operacional, custo por categoria, margem e comparação contra receita/simulações, sem decidir aceite.",
  },
  rh: {
    title: "RH",
    navLabel: "RH",
    route: "/todogreen/rh",
    area: "rh",
    status: "functional",
    permission: "hr:manage",
    description: "Pessoas, motoristas, escalas, documentos, alocação, dados sensíveis e rotinas trabalhistas.",
  },
  "dp-rh": {
    title: "Departamento Pessoal",
    navLabel: "DP",
    route: "/todogreen/dp",
    area: "dp",
    status: "functional",
    permission: "hr:manage",
    description: "Administração de pessoal, documentação, alocação e rotinas trabalhistas separadas do Financeiro.",
  },
  "motorista-frota": {
    title: "Frota e motoristas",
    navLabel: "Veículos e motoristas",
    route: "/todogreen/motorista-frota",
    area: "operacao",
    status: "functional",
    permission: ["fleet:manage", "operations:manage", "hr:manage"],
    description: "Gestão operacional de frota, motoristas, telemetria disponível, custo, bateria, manutenção e alertas.",
  },
  marketing: {
    title: "Inteligência de mercado",
    navLabel: "Notícias e inteligência",
    route: "/todogreen/marketing",
    area: "commercial",
    status: "functional",
    permission: "market:read",
    description: "Pesquisa de notícias, RFQs e possíveis decisores no mercado inteiro, com fonte e classificação.",
  },
  relatorios: {
    title: "Relatórios executivos",
    navLabel: "Relatórios",
    route: "/todogreen/relatorios",
    area: "gestao",
    status: "functional",
    description: "Resumo comercial, financeiro, operacional e ESG pronto para comitê, proposta ou prestação de contas.",
  },
  metodologia: {
    title: "Metodologia e premissas",
    navLabel: "Metodologia",
    route: "/todogreen/metodologia",
    area: "esg",
    status: "functional",
    description: "Fatores ambientais, fórmulas, versão, governança, disclaimer e evidências exigidas por produto.",
  },
  documentos: {
    title: "Documentos",
    navLabel: "Documentos",
    route: "/todogreen/documentos",
    area: "documentos",
    status: "functional",
    description:
      "Notas, telemetria, contratos, comprovantes e laudos que sustentam os números. Cada arquivo entra com impressão digital do conteúdo e sai por link temporário.",
  },
  "deal-desk": {
    title: "Aprovação de condição comercial",
    navLabel: "Aprovações",
    route: "/todogreen/deal-desk",
    area: "comercial",
    status: "functional",
    description:
      "Pedido, alçada, prazo, versão, comentários, decisão e histórico imutável. Enquanto pende, a proposta daquela simulação não sai.",
  },
  auditoria: {
    title: "Auditoria e governança",
    navLabel: "Auditoria",
    route: "/todogreen/auditoria",
    area: "administracao",
    status: "functional",
    description: "Permissões por papel, rastreabilidade de cálculo, bloqueios e fluxo de aprovação.",
  },
  acessos: {
    title: "Acessos",
    navLabel: "Acessos",
    route: "/todogreen/acessos",
    area: "administracao",
    status: "functional",
    // Quem não gerencia acessos não vê a aba. A checagem é o papel do vínculo,
    // não a presença da palavra "admin" em algum lugar da tela.
    permission: "access:manage",
    description: "Quem entra no espaço e o que cada pessoa pode fazer.",
  },
  integracoes: {
    title: "Integrações de IA, busca e automação",
    navLabel: "Integrações",
    route: "/todogreen/integracoes",
    area: "administracao",
    status: "functional",
    permission: "integration:manage",
    description: "Estado da cascata de IA, pesquisa web e automações autohospedadas, sem expor credenciais.",
  },
  conectores: {
    title: "Conectores de negócio",
    navLabel: "Conectores",
    route: "/todogreen/conectores",
    area: "administracao",
    status: "functional",
    // Conector de negócio (monday.com etc.) é diferente das telas técnicas
    // dev-only: administrar integrações basta. Owner/admin/operações veem.
    permission: "integration:manage",
    description: "Autorização das contas externas de negócio (monday.com e afins), sem expor credenciais.",
  },
  qualidade: {
    title: "Qualidade",
    navLabel: "Qualidade",
    route: "/todogreen/qualidade",
    area: "qualidade",
    status: "functional",
    permission: ["audit:read", "operations:manage", "evidence:manage"],
    description: "SLA, BSC, auditoria de execução, não conformidades, planos de ação e melhoria contínua.",
  },
  juridico: {
    title: "Jurídico",
    navLabel: "Jurídico",
    route: "/todogreen/juridico",
    area: "juridico",
    status: "functional",
    permission: ["proposal:manage", "deal:review", "deal:approve", "audit:read"],
    description: "Contratos, minutas, riscos jurídicos, aprovações e documentos formais vinculados à operação.",
  },
  indicadores: {
    title: "Indicadores",
    navLabel: "KPIs por área",
    route: "/todogreen/indicadores",
    area: "indicadores",
    status: "functional",
    description: "KPIs comerciais, operacionais, financeiros, ESG, qualidade, implantação e produtividade por área.",
  },
  administracao: {
    title: "Administração",
    navLabel: "Governança",
    route: "/todogreen/administracao",
    area: "administracao",
    status: "functional",
    permission: ["access:manage", "integration:manage", "audit:read"],
    description: "Acessos, permissões, auditoria, configurações e governança do ambiente To Do Green.",
  },
  "saude-sistema": {
    title: "Saúde do sistema",
    navLabel: "Saúde do sistema",
    route: "/todogreen/saude-sistema",
    area: "administracao",
    status: "functional",
    permission: ["integration:manage", "audit:read"],
    description: "Versão publicada (local × servidor × banco), componentes da plataforma e estado honesto de cada integração — com métricas e teste.",
  },
  "central-rfq": {
    title: "Central de RFQ e RFI",
    navLabel: "RFQ e RFI",
    route: "/todogreen/central-rfq",
    area: "comercial",
    status: "functional",
    // Ler é aberto a quem responde cotação; cadastrar documento oficial exige
    // `compliance:manage`, checado no servidor.
    description: "Acervo de habilitação com semáforo de validade, kits conferidos antes de enviar e o ciclo do RFQ do e-mail ao resultado.",
  },
  "sobre-o-negocio": {
    title: "Sobre o negócio",
    navLabel: "Sobre o negócio",
    route: "/todogreen/sobre-o-negocio",
    area: "administracao",
    status: "functional",
    // Ler é aberto a quem entra na vertical: um vendedor precisa saber a
    // história da casa para responder um RFI sem inventar. Editar exige
    // `business:teach`, checado no servidor — a tela só esconde o botão.
    description: "O dossiê que a IA lê antes de responder: identidade, proposta, operação, números com fonte, habilitação e o que ela aprendeu.",
  },
  planner: {
    title: "Planner",
    navLabel: "Planner",
    route: "/todogreen/planner",
    area: "produtividade",
    status: "functional",
    permission: "planner:manage",
    description: "Planos com tarefas, prazo, prioridade e checklist.",
  },
  // Blocos das 6 lacunas dos 26 blocos All Green — cada tela abre uma rota
  // canônica de módulo do TODO_GREEN_MODULE_CATALOG e mora na área dona do
  // assunto. Read-only + simulador; a conexão com dado real vem em rodadas
  // seguintes.
  "tenant-acessos": {
    title: "Perfis e permissões",
    navLabel: "Perfis e permissões",
    route: "/todogreen/tenant-acessos",
    area: "administracao",
    status: "functional",
    description: "Matriz de papéis internos/externos, capacidades por papel e blindagem contra vazamento de capacidade interna em papel externo.",
  },
  "green-on-empresa": {
    title: "Green On · B2B",
    navLabel: "Green On · B2B",
    route: "/todogreen/green-on-empresa",
    area: "financeiro",
    status: "functional",
    permission: "finance:manage",
    description: "Conta corporativa Green On: limite por sessão/dia/mês, autorização antes de cobrar, fatura consolidada e custo por km.",
  },
  "roaming-ocpi": {
    title: "Roaming OCPI",
    navLabel: "Roaming OCPI",
    route: "/todogreen/roaming-ocpi",
    area: "operacao",
    status: "functional",
    description: "Identificador OCPI, whitelist do token da rede parceira e rateio de sessão CPO / eMSP / cliente.",
  },
  "energia-peak": {
    title: "Energia · BESS e pico",
    navLabel: "BESS e pico",
    route: "/todogreen/energia-peak",
    area: "esg",
    status: "functional",
    description: "Peak shaving contra a demanda contratada, mix rede/solar/BESS, fração renovável efetiva e perda tomada→bateria.",
  },
  "fila-alertas": {
    title: "Fila de alertas",
    navLabel: "Fila de alertas",
    route: "/todogreen/fila-alertas",
    area: "operacao",
    status: "functional",
    description: "Alertas com severidade e SLA por criticidade, teto por operador (crítico nunca rebaixa) e taxa de falso positivo por regra.",
  },
  "greenmob-locacao": {
    title: "Greenmob · Locação",
    navLabel: "Greenmob · Locação",
    route: "/todogreen/greenmob-locacao",
    area: "frota",
    status: "functional",
    description: "Contrato de locação, avaria por momento (pré-existente ≠ cobrança), cobrança final derivada e devolução.",
  },
  "saas-billing": {
    title: "SaaS · Billing",
    navLabel: "SaaS · Billing",
    route: "/todogreen/saas-billing",
    area: "administracao",
    status: "functional",
    permission: "finance:manage",
    description: "Contratação por módulo e métrica: base + excedente sobre franquia, desconto anual só se anual, análise de downgrade.",
  },
  // Rodada P0/P1/P2 — bases arquiteturais e produtos externos.
  "core-grupo": {
    title: "Core All Green",
    navLabel: "Core do Grupo",
    route: "/todogreen/core-grupo",
    area: "administracao",
    status: "functional",
    description: "Veículo, motorista, carregador e conta como registros do Grupo — cada negócio (TDG, Green On, Greenmob) enxerga por exposição declarada. UMA linha compartilhada em vez de três duplicadas.",
  },
  "ocpp-console": {
    title: "OCPP Console",
    navLabel: "OCPP Console",
    route: "/todogreen/ocpp-console",
    area: "operacao",
    status: "functional",
    description: "Valida CALL do carregador, gera CALLRESULT, monta comandos CSMS-initiated (RemoteStart/Stop, UnlockConnector) e simula a máquina de estado do conector segundo OCPP 1.6-J.",
  },
  "green-on-app": {
    title: "Green On App · B2C",
    navLabel: "Green On App",
    route: "/todogreen/green-on-app",
    area: "operacao",
    status: "functional",
    description: "Jornada do usuário fim-a-fim: buscar estação, reservar com tolerância, autenticar por QR, sessão ao vivo com preço travado, pagamento e recibo.",
  },
  "seguranca-fisica": {
    title: "Segurança física",
    navLabel: "Segurança física",
    route: "/todogreen/seguranca-fisica",
    area: "operacao",
    status: "functional",
    description: "Bloqueio remoto com barreiras (contexto proibido, velocidade, dupla autorização), senha de coação e escalonamento por inexecução de contato.",
  },
});
