// Configuração do formulário de precificação — JS puro, sem React: o rótulo
// de cada premissa, quais campos são texto ou sim/não, a frota disponível e
// os valores com que cada produto abre.

export const fieldLabels = {
  allocationPercent: "Alocação da rota (%)",
  cashFlowMonths: "Meses de fluxo de caixa",
  chargingWindow: "Janela de recarga",
  city: "Cidade",
  client: "Cliente",
  clientId: "ID do cliente",
  clientsOnRoute: "Clientes na rota",
  components: "Componentes do projeto",
  consolidationPercent: "Consolidação (%)",
  contractMonths: "Meses de contrato",
  customerTargetPrice: "Target do cliente",
  daysPerMonth: "Dias/mês",
  deliveryWindows: "Janelas de entrega",
  density: "Densidade da rota",
  deliveries: "Entregas",
  destination: "Destino",
  distanceKm: "Distância km",
  driverShift: "Turno do motorista",
  drivers: "Motoristas",
  frequencyPerMonth: "Frequência/mês",
  hazmat: "Carga perigosa",
  helpers: "Ajudantes",
  hoursPerDay: "Horas/dia",
  implementationCost: "Implantação R$",
  initialInvestment: "Investimento inicial R$",
  kmPerRoute: "Km por rota",
  licenseCost: "Licenças R$",
  lossPercent: "Perda técnica (%)",
  materialType: "Tipo de material",
  occupancyPercent: "Ocupação (%)",
  origin: "Origem",
  packages: "Pacotes",
  pallets: "Pallets",
  peakSeasonFactor: "Fator pico sazonal",
  points: "Pontos atendidos",
  reserveVehicle: "Veículo reserva",
  returnLoaded: "Retorno carregado",
  reverseLogistics: "Logística reversa",
  riskManagementCost: "Gerenciamento de risco R$",
  routesPerDay: "Rotas/dia",
  services: "Serviços inclusos",
  sharedRouteCost: "Custo rota compartilhada R$",
  sla: "SLA",
  stops: "Paradas",
  stores: "Lojas",
  strategicContract: "Contrato estratégico",
  successRate: "Sucesso entrega (%)",
  suppliers: "Fornecedores",
  supervisionCost: "Supervisão R$",
  technologyCost: "Tecnologia R$",
  temperatureControlled: "Temperatura controlada",
  tollCost: "Pedágio por viagem R$",
  tons: "Toneladas",
  trainingCost: "Treinamento R$",
  tripsPerMonth: "Viagens/mês",
  unloadingHours: "Horas descarga",
  vehicles: "Quantidade de veículos",
  returnsRate: "Devoluções (%)",
  cleaningCost: "Limpeza e higienização R$",
  quantity: "Quantidade",
  vehicleType: "Tipo de veículo",
  visitsPerMonth: "Visitas/mês",
  volumeM3: "Volume m³",
  waitingHours: "Horas de espera",
  weeklyFrequency: "Frequência semanal",
  weightKg: "Peso kg",
  dataQuality: "Quanto podemos confiar nos dados (%)",
};

export const textFields = new Set([
  "city",
  "client",
  "clientId",
  "components",
  "deliveryWindows",
  "destination",
  "driverShift",
  "materialType",
  "origin",
  "services",
  "sla",
  "vehicleType",
]);

export const booleanFields = new Set([
  "hazmat",
  "reserveVehicle",
  "returnLoaded",
  "reverseLogistics",
  "strategicContract",
  "temperatureControlled",
]);

// Frota da To Do Green (arquivo de referência tipos_operacao.yaml — frota
// disponível). "Tipo de veículo" é uma escolha, e cada veículo tem um custo de
// referência na régua (VEHICLE_COST_REFERENCE, em pricingParametersDomain), então
// SELECIONAR muda o preço — e o admin ajusta o custo por veículo na Régua.
export const VEHICLE_TYPES = Object.freeze([
  "Moto",
  "Passeio",
  "Fiorino / Van",
  "VUC",
  "Toco",
  "Truck",
  "Carreta Sider",
  "Carreta Aberta",
  "Carreta elétrica",
  "Cavalo elétrico (solo)",
]);

// Toda premissa que muda preço, margem ou CO₂ nasce vazia.
//
// Antes a calculadora abria com distância, frequência, ocupação, tipo de
// veículo e confiança no dado já preenchidos. Em um segundo havia preço,
// margem, CO₂ evitado e recomendação na tela — todos calculados sobre números
// que ninguém informou. Um resultado assim é indistinguível de um cálculo
// real, e foi assim que ele chegou a proposta e a relatório.
//
// Ficam só os campos que são de fato neutros: custo que começa em zero porque
// pode não existir (pedágio, treinamento, implantação), opção de sim/não com
// resposta padrão, e o alvo do cliente, que é zero enquanto ele não disser.
export const productDefaults = {
  "middle-mile": {
    client: "",
    origin: "",
    destination: "",
    distanceKm: "",
    tripsPerMonth: "",
    vehicleType: "",
    pallets: "",
    weightKg: "",
    tollCost: 0,
    waitingHours: "",
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
  "middle-mile-spot": {
    client: "",
    origin: "",
    destination: "",
    distanceKm: "",
    tripsPerMonth: 1,
    vehicleType: "",
    pallets: "",
    weightKg: "",
    tollCost: 0,
    waitingHours: "",
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
    modality: "spot",
  },
  "last-mile": {
    client: "",
    city: "",
    packages: "",
    routesPerDay: "",
    daysPerMonth: "",
    kmPerRoute: "",
    vehicleType: "",
    stops: "",
    successRate: "",
    returnsRate: "",
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
  dedicated: {
    client: "",
    vehicles: "",
    vehicleType: "",
    drivers: "",
    helpers: "",
    hoursPerDay: "",
    daysPerMonth: "",
    reserveVehicle: false,
    supervisionCost: 0,
    technologyCost: 0,
    trainingCost: 0,
    implementationCost: 0,
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
  transfer: {
    client: "",
    origin: "",
    destination: "",
    distanceKm: "",
    frequencyPerMonth: "",
    vehicleType: "",
    pallets: "",
    weightKg: "",
    waitingHours: "",
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
  "store-replenishment": {
    client: "",
    stores: "",
    visitsPerMonth: "",
    kmPerRoute: "",
    vehicleType: "",
    helpers: "",
    unloadingHours: "",
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
  "supplier-pickup": {
    client: "",
    suppliers: "",
    frequencyPerMonth: "",
    distanceKm: "",
    vehicleType: "",
    waitingHours: "",
    consolidationPercent: "",
    weightKg: "",
    pallets: "",
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
  "fractional-distribution": {
    client: "",
    sharedRouteCost: "",
    allocationPercent: "",
    deliveries: "",
    distanceKm: "",
    clientsOnRoute: "",
    occupancyPercent: "",
    weightKg: "",
    volumeM3: 36,
    customerTargetPrice: 0,
    dataQuality: "",
  },
  bulk: {
    client: "",
    materialType: "",
    tons: "",
    distanceKm: "",
    tripsPerMonth: "",
    vehicleType: "",
    cleaningCost: 0,
    waitingHours: "",
    lossPercent: 0,
    licenseCost: 0,
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
  "custom-project": {
    client: "",
    components: "",
    contractMonths: "",
    initialInvestment: 0,
    cashFlowMonths: "",
    customerTargetPrice: 0,
    occupancyPercent: "",
    dataQuality: "",
  },
};
