// Gerado a partir da tabela oficial de status/de-para da Track3r
// (Status-DexPara-Track3r-Sequencial-Completo.xlsx, enviada pelo Lucas em 23/09/2026).
// Fonte da verdade dos códigos de status; a categoria é uma classificação
// conservadora para os KPIs (entregue/insucesso/avaria/extravio/devolução/…).
// Ambíguos ficam 'em_transito'/'outro' — nunca contam como insucesso por engano.
// Ajuste pontual de categoria é seguro: é só editar o campo aqui.

export const TRACK3R_STATUS_CODES = Object.freeze([
  { codigo: "1", descricao: "Arquivo Recebido", correios: false, categoria: "em_transito" },
  { codigo: "2", descricao: "Entregue", correios: false, categoria: "entregue" },
  { codigo: "3", descricao: "Em Rota", correios: false, categoria: "em_transito" },
  { codigo: "4", descricao: "Liberado", correios: false, categoria: "em_transito" },
  { codigo: "5", descricao: "A Devolver Origem", correios: false, categoria: "devolucao" },
  { codigo: "6", descricao: "A caminho do destinatário", correios: false, categoria: "em_transito" },
  { codigo: "15", descricao: "Estornado", correios: false, categoria: "cancelado" },
  { codigo: "16", descricao: "Reentregar", correios: false, categoria: "em_transito" },
  { codigo: "18", descricao: "Geração de lista", correios: false, categoria: "em_transito" },
  { codigo: "21", descricao: "Extravio Total - Armazém", correios: false, categoria: "extravio" },
  { codigo: "22", descricao: "Recebido pela transportadora", correios: false, categoria: "em_transito" },
  { codigo: "23", descricao: "Cancelamento de lista", correios: false, categoria: "cancelado" },
  { codigo: "25", descricao: "Cancelamento de status finalizador", correios: false, categoria: "cancelado" },
  { codigo: "27", descricao: "Excluída da lista", correios: false, categoria: "cancelado" },
  { codigo: "29", descricao: "Em Transferência", correios: false, categoria: "transferencia" },
  { codigo: "30", descricao: "Transferido", correios: false, categoria: "transferencia" },
  { codigo: "31", descricao: "Falta no recebimento de transferência", correios: false, categoria: "extravio" },
  { codigo: "33", descricao: "Devolução em Transferência", correios: false, categoria: "devolucao" },
  { codigo: "34", descricao: "Devolução Transferida", correios: false, categoria: "devolucao" },
  { codigo: "35", descricao: "Devolução em Rota", correios: false, categoria: "devolucao" },
  { codigo: "37", descricao: "Devolvido", correios: false, categoria: "devolucao" },
  { codigo: "38", descricao: "Ocorrência", correios: false, categoria: "outro" },
  { codigo: "40", descricao: "Recebido no CD Ocorrência", correios: false, categoria: "em_transito" },
  { codigo: "41", descricao: "Recebido no CD", correios: false, categoria: "em_transito" },
  { codigo: "42", descricao: "Recebido no CD Reentregar", correios: false, categoria: "em_transito" },
  { codigo: "44", descricao: "Suspeita de extravio", correios: false, categoria: "extravio" },
  { codigo: "47", descricao: "Recebido no CD Parcial", correios: false, categoria: "em_transito" },
  { codigo: "49", descricao: "Extravio Total - Motorista", correios: false, categoria: "extravio" },
  { codigo: "50", descricao: "Avaria Parcial - Armazém", correios: false, categoria: "avaria" },
  { codigo: "51", descricao: "Avaria Parcial - Motorista", correios: false, categoria: "avaria" },
  { codigo: "52", descricao: "Avaria Total - Armazém", correios: false, categoria: "avaria" },
  { codigo: "53", descricao: "Avaria Total - Motorista", correios: false, categoria: "avaria" },
  { codigo: "58", descricao: "Recebido no CD A Devolver", correios: false, categoria: "devolucao" },
  { codigo: "60", descricao: "Agendado", correios: false, categoria: "agendamento" },
  { codigo: "62", descricao: "Pedido Cancelado", correios: false, categoria: "cancelado" },
  { codigo: "64", descricao: "Transferência de lista", correios: false, categoria: "transferencia" },
  { codigo: "66", descricao: "Encomenda finalizada por limite máximo de tratativas", correios: false, categoria: "outro" },
  { codigo: "68", descricao: "Salvados", correios: false, categoria: "extravio" },
  { codigo: "70", descricao: "Sinistro Aguardando Seguradora", correios: false, categoria: "extravio" },
  { codigo: "72", descricao: "Sinistro Solucionado", correios: false, categoria: "extravio" },
  { codigo: "114", descricao: "Calendarizado", correios: false, categoria: "agendamento" },
  { codigo: "118", descricao: "Tratado automaticamente pelo App", correios: false, categoria: "em_transito" },
  { codigo: "122", descricao: "Geração de lista de subcontrato", correios: false, categoria: "em_transito" },
  { codigo: "124", descricao: "CT-e autorizado", correios: false, categoria: "fiscal" },
  { codigo: "127", descricao: "Aguardando Agendamento", correios: false, categoria: "agendamento" },
  { codigo: "130", descricao: "Aguardando liberação pelo embarcador", correios: false, categoria: "em_transito" },
  { codigo: "131", descricao: "Arquivo Enviado", correios: false, categoria: "em_transito" },
  { codigo: "133", descricao: "Insucesso no Agendamento", correios: false, categoria: "insucesso" },
  { codigo: "137", descricao: "Análise de Perda", correios: false, categoria: "em_transito" },
  { codigo: "138", descricao: "Perda de Inventário", correios: false, categoria: "extravio" },
  { codigo: "139", descricao: "Inventário Localizado", correios: false, categoria: "em_transito" },
  { codigo: "237", descricao: "Avaria aguardando análise de cobrança", correios: false, categoria: "avaria" },
  { codigo: "247", descricao: "A entrega do objeto está condicionada à composição do lote", correios: true, categoria: "insucesso" },
  { codigo: "248", descricao: "A entrega não pode ser efetuada", correios: true, categoria: "insucesso" },
  { codigo: "249", descricao: "A entrega não pode ser efetuada - Carteiro não atendido", correios: true, categoria: "insucesso" },
  { codigo: "250", descricao: "A entrega não pode ser efetuada - Cliente desconhecido no local", correios: true, categoria: "insucesso" },
  { codigo: "251", descricao: "A entrega não pode ser efetuada - Cliente mudou-se", correios: true, categoria: "insucesso" },
  { codigo: "252", descricao: "A entrega não pode ser efetuada - Cliente recusou- se a receber", correios: true, categoria: "insucesso" },
  { codigo: "253", descricao: "A entrega não pode ser efetuada - Destinatário não apresentou documento exigido", correios: true, categoria: "insucesso" },
  { codigo: "254", descricao: "A entrega não pode ser efetuada - Empresa sem expediente", correios: true, categoria: "insucesso" },
  { codigo: "255", descricao: "A entrega não pode ser efetuada - Endereço incorreto", correios: true, categoria: "insucesso" },
  { codigo: "256", descricao: "A entrega não pode ser efetuada - Logradouro com numeração irregular", correios: true, categoria: "insucesso" },
  { codigo: "257", descricao: "A importação do objeto/conteúdo não foi autorizada pelos órgãos fiscalizadores", correios: true, categoria: "outro" },
  { codigo: "258", descricao: "Área com distribuição sujeita a prazo diferenciado", correios: true, categoria: "outro" },
  { codigo: "259", descricao: "As dimensões do objeto impossibilitam o tratamento e a entrega", correios: true, categoria: "insucesso" },
  { codigo: "260", descricao: "Coleta ou entrega de objeto não efetuada", correios: true, categoria: "insucesso" },
  { codigo: "261", descricao: "Declaração aduaneira ausente ou incorreta", correios: true, categoria: "insucesso" },
  { codigo: "262", descricao: "Destinatário não retirou objeto na Unidade dos Correios", correios: true, categoria: "insucesso" },
  { codigo: "263", descricao: "Entrega de objeto bloqueada a pedido do remetente", correios: true, categoria: "insucesso" },
  { codigo: "264", descricao: "Favor desconsiderar a informação anterior", correios: true, categoria: "outro" },
  { codigo: "265", descricao: "Lote de objetos incompleto", correios: true, categoria: "insucesso" },
  { codigo: "266", descricao: "Objeto aguardando retirada no endereço indicado", correios: true, categoria: "insucesso" },
  { codigo: "267", descricao: "Objeto apreendido por órgão de fiscalização ou outro órgão anuente", correios: true, categoria: "insucesso" },
  { codigo: "268", descricao: "Objeto coletado", correios: true, categoria: "coleta" },
  { codigo: "269", descricao: "Objeto com atraso na entrega", correios: true, categoria: "outro" },
  { codigo: "270", descricao: "Objeto com data de entrega agendada", correios: true, categoria: "agendamento" },
  { codigo: "271", descricao: "Objeto devolvido ao remetente", correios: true, categoria: "devolucao" },
  { codigo: "272", descricao: "Objeto devolvido aos Correios", correios: true, categoria: "devolucao" },
  { codigo: "273", descricao: "Objeto disponível para retirada em Caixa Postal", correios: true, categoria: "outro" },
  { codigo: "274", descricao: "Objeto e/ou conteúdo avariado", correios: true, categoria: "avaria" },
  { codigo: "275", descricao: "Objeto e/ou conteúdo avariado por acidente com veículo", correios: true, categoria: "avaria" },
  { codigo: "276", descricao: "Objeto encaminhado para", correios: true, categoria: "em_transito" },
  { codigo: "277", descricao: "Objeto endereçado à empresa falida", correios: true, categoria: "insucesso" },
  { codigo: "278", descricao: "Objeto entregue ao destinatário", correios: true, categoria: "entregue" },
  { codigo: "279", descricao: "Objeto Extraviado", correios: true, categoria: "extravio" },
  { codigo: "280", descricao: "Objeto liberado pela alfândega", correios: true, categoria: "em_transito" },
  { codigo: "281", descricao: "Objeto mal encaminhado", correios: true, categoria: "em_transito" },
  { codigo: "282", descricao: "Objeto não localizado", correios: true, categoria: "extravio" },
  { codigo: "283", descricao: "Objeto postado", correios: true, categoria: "em_transito" },
  { codigo: "284", descricao: "Objeto postado após o horário limite da agência", correios: true, categoria: "em_transito" },
  { codigo: "285", descricao: "Objeto recebido em", correios: true, categoria: "em_transito" },
  { codigo: "286", descricao: "Objeto recebido na unidade de distribuição", correios: true, categoria: "em_transito" },
  { codigo: "287", descricao: "Objeto recebido na unidade de exportação", correios: true, categoria: "em_transito" },
  { codigo: "288", descricao: "Objeto recebido na Unidade dos Correios", correios: true, categoria: "em_transito" },
  { codigo: "289", descricao: "Objeto recebido no Brasil", correios: true, categoria: "em_transito" },
  { codigo: "290", descricao: "Objeto reimpresso e reenviado", correios: true, categoria: "em_transito" },
  { codigo: "291", descricao: "Objeto roubado", correios: true, categoria: "extravio" },
  { codigo: "292", descricao: "Objeto saiu para entrega ao destinatário", correios: true, categoria: "em_transito" },
  { codigo: "293", descricao: "Objeto saiu para entrega ao remetente", correios: true, categoria: "em_transito" },
  { codigo: "294", descricao: "Objeto será devolvido por solicitação do remetente", correios: true, categoria: "devolucao" },
  { codigo: "295", descricao: "Para recebimento do objeto, é necessário o pagamento do ICMS Importação", correios: true, categoria: "outro" },
  { codigo: "296", descricao: "Remetente não retirou objeto na Unidade dos Correios", correios: true, categoria: "insucesso" },
  { codigo: "297", descricao: "Retirada em Unidade dos Correios não autorizada pelo remetente", correios: true, categoria: "insucesso" },
  { codigo: "298", descricao: "Revisão de tributo concluída - Objeto liberado", correios: true, categoria: "em_transito" },
  { codigo: "299", descricao: "Revisão de tributo concluída - Tributo alterado", correios: true, categoria: "outro" },
  { codigo: "300", descricao: "Revisão de tributo concluída - Tributo mantido", correios: true, categoria: "outro" },
  { codigo: "301", descricao: "Saída para entrega cancelada", correios: true, categoria: "insucesso" },
  { codigo: "302", descricao: "Solicitada revisão do tributo estabelecido", correios: true, categoria: "outro" },
  { codigo: "303", descricao: "Tentativa de entrega não efetuada", correios: true, categoria: "insucesso" },
  { codigo: "304", descricao: "Suspensão de entrega por embarcador inadimplente", correios: false, categoria: "outro" },
  { codigo: "305", descricao: "Aguardando coleta pela transportadora", correios: false, categoria: "coleta" },
  { codigo: "241", descricao: "Coletado pela Transportadora", correios: false, categoria: "coleta" },
  { codigo: "306", descricao: "Ressarcimento em Tratativa", correios: false, categoria: "em_transito" },
  { codigo: "307", descricao: "Ressarcimento Pago", correios: false, categoria: "em_transito" },
  { codigo: "246", descricao: "Autorizado Reentrega pelo CD", correios: false, categoria: "em_transito" },
  { codigo: "245", descricao: "Autorizado A Devolver Origem pelo CD", correios: false, categoria: "devolucao" },
  { codigo: "308", descricao: "Falta no recebimento da conferência", correios: false, categoria: "extravio" },
  { codigo: "309", descricao: "Entrega aceita pela transportadora", correios: false, categoria: "em_transito" },
  { codigo: "310", descricao: "Nenhuma transportadora disponível para a coleta", correios: false, categoria: "coleta" },
  { codigo: "311", descricao: "Não foi possivel realizar a integração com a transportadora", correios: false, categoria: "em_transito" },
  { codigo: "244", descricao: "Geração de lista de redespacho", correios: false, categoria: "em_transito" },
  { codigo: "242", descricao: "Geração de lista de integração", correios: false, categoria: "em_transito" },
  { codigo: "312", descricao: "Aguardando definição de transportadora", correios: false, categoria: "em_transito" },
  { codigo: "313", descricao: "Aguardando programação de coleta", correios: false, categoria: "coleta" },
  { codigo: "314", descricao: "Solicitação de coleta realizada", correios: false, categoria: "coleta" },
  { codigo: "315", descricao: "Em rota para coleta no embarcador", correios: false, categoria: "coleta" },
  { codigo: "316", descricao: "Coletado no Embarcador", correios: false, categoria: "coleta" },
  { codigo: "243", descricao: "Redespachado", correios: false, categoria: "em_transito" },
  { codigo: "363", descricao: "Avaria - aguardando reposição de peça", correios: false, categoria: "avaria" },
  { codigo: "364", descricao: "Reposição de peça realizada", correios: false, categoria: "em_transito" },
  { codigo: "365", descricao: "Coleta não realizada", correios: false, categoria: "insucesso" },
  { codigo: "368", descricao: "Consolidada", correios: false, categoria: "em_transito" },
  { codigo: "369", descricao: "Desconsolidada", correios: false, categoria: "em_transito" },
  { codigo: "374", descricao: "Falta na desconsolidação", correios: false, categoria: "extravio" },
  { codigo: "377", descricao: "Consolidação cancelada", correios: false, categoria: "cancelado" },
  { codigo: "380", descricao: "Aguardando informações do arquivo", correios: false, categoria: "em_transito" },
  { codigo: "381", descricao: "Mercadoria Apreendida", correios: false, categoria: "insucesso" },
  { codigo: "382", descricao: "Analise Controle de Qualidade", correios: false, categoria: "em_transito" },
  { codigo: "383", descricao: "Aprovado Controle de Qualidade", correios: false, categoria: "em_transito" },
  { codigo: "384", descricao: "Recusado Controle de Qualidade", correios: false, categoria: "insucesso" },
  { codigo: "385", descricao: "Em Análise de Indenização", correios: false, categoria: "em_transito" },
  { codigo: "386", descricao: "Tratativa de Indenização", correios: false, categoria: "outro" },
  { codigo: "387", descricao: "Ressarcimento Negado", correios: false, categoria: "em_transito" },
  { codigo: "388", descricao: "Solicitação Baixa Interna", correios: false, categoria: "outro" },
  { codigo: "389", descricao: "Baixa Interna Negada", correios: false, categoria: "outro" },
  { codigo: "390", descricao: "Baixada Internamente", correios: false, categoria: "outro" },
  { codigo: "391", descricao: "Extravio Total - Parceiro", correios: false, categoria: "extravio" },
  { codigo: "392", descricao: "Aguardando geração de lista de subcontrato", correios: false, categoria: "em_transito" },
  { codigo: "393", descricao: "Atraso na Entrega", correios: false, categoria: "outro" },
  { codigo: "475", descricao: "Em Transferência com Ocorrência", correios: false, categoria: "transferencia" },
  { codigo: "486", descricao: "Recebimento de Devolução", correios: false, categoria: "devolucao" },
  { codigo: "487", descricao: "Falta no Recebimento de Devolução", correios: false, categoria: "extravio" },
  { codigo: "492", descricao: "Retirado pelo destinatário", correios: false, categoria: "entregue" },
  { codigo: "494", descricao: "Aguardando tratativa/analise para devolução", correios: false, categoria: "devolucao" },
  { codigo: "501", descricao: "Extravio Parcial - Armazém", correios: false, categoria: "extravio" },
  { codigo: "502", descricao: "Extravio Parcial - Motorista", correios: false, categoria: "extravio" },
  { codigo: "503", descricao: "Extravio Parcial - Parceiro", correios: false, categoria: "extravio" },
  { codigo: "504", descricao: "Entrega Barrada", correios: false, categoria: "insucesso" },
  { codigo: "506", descricao: "Avaria identificada no recebimento da carga", correios: false, categoria: "avaria" },
  { codigo: "509", descricao: "Descarte", correios: false, categoria: "outro" },
  { codigo: "510", descricao: "Apropriação", correios: false, categoria: "em_transito" },
  { codigo: "511", descricao: "Chegada ao aeroporto", correios: false, categoria: "em_transito" },
  { codigo: "512", descricao: "Saida do Aeroporto Origem", correios: false, categoria: "em_transito" },
  { codigo: "513", descricao: "Chegada ao aeroporto destino", correios: false, categoria: "em_transito" },
  { codigo: "514", descricao: "Aguardando Faturamento", correios: false, categoria: "em_transito" },
  { codigo: "515", descricao: "Sinistro não solucionado", correios: false, categoria: "extravio" },
  { codigo: "517", descricao: "Aéreo - Documento recebido", correios: false, categoria: "em_transito" },
  { codigo: "518", descricao: "Aéreo - Liberação de retenção", correios: false, categoria: "em_transito" },
  { codigo: "519", descricao: "Aéreo - Carga chegou em uma unidade de trânsito", correios: false, categoria: "em_transito" },
  { codigo: "520", descricao: "Aéreo - Retenção", correios: false, categoria: "em_transito" },
  { codigo: "521", descricao: "Aéreo - Carga enviada (Despachada)", correios: false, categoria: "em_transito" },
  { codigo: "522", descricao: "Aéreo - Carga entregue", correios: false, categoria: "entregue" },
  { codigo: "523", descricao: "Aéreo - Retornou para origem", correios: false, categoria: "devolucao" },
  { codigo: "524", descricao: "Aéreo - Carga Encontrada (Found)", correios: false, categoria: "em_transito" },
  { codigo: "525", descricao: "Aéreo - Cancelamento de entrega", correios: false, categoria: "cancelado" },
  { codigo: "526", descricao: "Aéreo - Retorno de entrega", correios: false, categoria: "devolucao" },
  { codigo: "527", descricao: "Aéreo - Carga manifestada", correios: false, categoria: "em_transito" },
  { codigo: "528", descricao: "Aéreo - Carga Perdida (Missing)", correios: false, categoria: "extravio" },
  { codigo: "529", descricao: "Aéreo - Carga saiu para entrega", correios: false, categoria: "em_transito" },
  { codigo: "530", descricao: "Aéreo - Recebida no destino - Mercadorias desembarcadas", correios: false, categoria: "em_transito" },
  { codigo: "531", descricao: "Aéreo - Carga aceita (Emitida)", correios: false, categoria: "em_transito" },
  { codigo: "532", descricao: "Aéreo - Corte de carga do despacho", correios: false, categoria: "em_transito" },
  { codigo: "533", descricao: "Aéreo - Recebida no ponto parceiro", correios: false, categoria: "em_transito" },
  { codigo: "534", descricao: "Aéreo - Transferência smart locker", correios: false, categoria: "transferencia" },
  { codigo: "535", descricao: "Aéreo - Transferência smart locker cancelada", correios: false, categoria: "cancelado" },
  { codigo: "536", descricao: "Pré-Lista", correios: false, categoria: "em_transito" },
  { codigo: "140", descricao: "Destinatario Retira Mercadoria na Transportadora", correios: false, categoria: "em_transito" },
  { codigo: "141", descricao: "Destinatario Alega Mercadoria Desac com Pedido", correios: false, categoria: "insucesso" },
  { codigo: "142", descricao: "Endereço do destinatário não localizado ou insuficiente", correios: false, categoria: "extravio" },
  { codigo: "143", descricao: "Entrega Prejudicada Pelo Horario/Transito", correios: false, categoria: "insucesso" },
  { codigo: "144", descricao: "Recusado Pelo Cliente Por Motivos Pessoais", correios: false, categoria: "insucesso" },
  { codigo: "145", descricao: "Destinatario Desconhecido", correios: false, categoria: "insucesso" },
  { codigo: "146", descricao: "Atraso Operacional", correios: false, categoria: "insucesso" },
  { codigo: "147", descricao: "Area de Risco > Solicito Novo Endereco de Entrega", correios: false, categoria: "insucesso" },
  { codigo: "148", descricao: "Pedido Em Analise de Extravio", correios: false, categoria: "extravio" },
  { codigo: "149", descricao: "Falta de Mercadoria", correios: false, categoria: "extravio" },
  { codigo: "150", descricao: "Mercadoria Avariada", correios: false, categoria: "avaria" },
  { codigo: "151", descricao: "Embalagem Avariada", correios: false, categoria: "avaria" },
  { codigo: "152", descricao: "Carga Roubada", correios: false, categoria: "extravio" },
  { codigo: "153", descricao: "Mercadoria Retida Pela Fiscalização", correios: false, categoria: "outro" },
  { codigo: "154", descricao: "Não Visitado", correios: false, categoria: "outro" },
  { codigo: "155", descricao: "Devolução Autorizada pelo Remetente", correios: false, categoria: "devolucao" },
  { codigo: "156", descricao: "Mercadoria trocada na entrega", correios: false, categoria: "outro" },
  { codigo: "157", descricao: "Recusa por pedido cancelado", correios: false, categoria: "cancelado" },
  { codigo: "158", descricao: "Cliente mudou de endereço", correios: false, categoria: "outro" },
  { codigo: "159", descricao: "Destinatario Ausente", correios: false, categoria: "insucesso" },
  { codigo: "160", descricao: "Recusado", correios: false, categoria: "insucesso" },
  { codigo: "186", descricao: "Destinatário Ausente 1a Tentativa", correios: false, categoria: "insucesso" },
  { codigo: "187", descricao: "Destinatário Ausente 2a Tentativa", correios: false, categoria: "insucesso" },
  { codigo: "188", descricao: "Destinatário Ausente 3a Tentativa", correios: false, categoria: "insucesso" },
  { codigo: "192", descricao: "Produto recusado na devolução pelo embarcador", correios: false, categoria: "insucesso" },
  { codigo: "194", descricao: "Produto não entra na residencia", correios: false, categoria: "outro" },
  { codigo: "195", descricao: "Entrega não efetuada - feriado local", correios: false, categoria: "insucesso" },
  { codigo: "196", descricao: "Excesso de chuva", correios: false, categoria: "outro" },
  { codigo: "197", descricao: "Dificuldades na região de entrega", correios: false, categoria: "outro" },
  { codigo: "219", descricao: "Cliente indisponível solicitou agendamento", correios: false, categoria: "agendamento" },
  { codigo: "221", descricao: "Greve / Manifestação / Paralisação", correios: false, categoria: "outro" },
  { codigo: "225", descricao: "Cep não atendido pela base", correios: false, categoria: "outro" },
  { codigo: "226", descricao: "Quebra de Veículo", correios: false, categoria: "outro" },
  { codigo: "231", descricao: "Número não localizado", correios: false, categoria: "extravio" },
  { codigo: "234", descricao: "Aguardando posicionamento Embarcador", correios: false, categoria: "em_transito" },
  { codigo: "239", descricao: "Local fechado", correios: false, categoria: "outro" },
  { codigo: "240", descricao: "Sem registro de entrada na transportadora", correios: false, categoria: "em_transito" },
  { codigo: "349", descricao: "Tentativa de roubo", correios: false, categoria: "outro" },
  { codigo: "350", descricao: "A carga está em análise pelo órgão fiscalizador", correios: false, categoria: "em_transito" },
  { codigo: "357", descricao: "Condomínio com restrição de horário", correios: false, categoria: "outro" },
  { codigo: "359", descricao: "Divergência na quantidade de volumes", correios: false, categoria: "outro" },
  { codigo: "362", descricao: "Epidemia - cliente solicitou reagendamento", correios: false, categoria: "agendamento" },
  { codigo: "352", descricao: "Mercadoria fora do padrão para o serviço prestado", correios: false, categoria: "outro" },
  { codigo: "356", descricao: "Destinatário Ausente - Portaria Eletrônica", correios: false, categoria: "insucesso" },
  { codigo: "367", descricao: "CT-e retido para conferência", correios: false, categoria: "fiscal" },
  { codigo: "394", descricao: "Local fechado para devolução", correios: false, categoria: "devolucao" },
  { codigo: "395", descricao: "Responsável pela devolução ausente", correios: false, categoria: "insucesso" },
  { codigo: "482", descricao: "Interdição de rodovia/estrada", correios: false, categoria: "outro" },
  { codigo: "496", descricao: "Fila de Espera", correios: false, categoria: "outro" },
  { codigo: "499", descricao: "Acidente na rodovia", correios: false, categoria: "outro" },
  { codigo: "540", descricao: "Cliente não dispõe do frete para entrega da mercadoria", correios: false, categoria: "outro" },
  { codigo: "683", descricao: "Saida da Fiscalização", correios: false, categoria: "em_transito" },
  { codigo: "7", descricao: "A Coletar", correios: false, categoria: "coleta" },
  { codigo: "8", descricao: "Coleta Impressa", correios: false, categoria: "coleta" },
  { codigo: "9", descricao: "Coleta Em Trânsito", correios: false, categoria: "coleta" },
  { codigo: "10", descricao: "Coletado", correios: false, categoria: "coleta" },
  { codigo: "11", descricao: "Em Transferência", correios: false, categoria: "transferencia" },
  { codigo: "12", descricao: "A Devolver Destino", correios: false, categoria: "devolucao" },
  { codigo: "13", descricao: "Devolvido", correios: false, categoria: "devolucao" },
  { codigo: "14", descricao: "Coleta Cancelada", correios: false, categoria: "cancelado" },
  { codigo: "17", descricao: "Transferido", correios: false, categoria: "transferencia" },
  { codigo: "19", descricao: "Estornado", correios: false, categoria: "cancelado" },
  { codigo: "20", descricao: "Extravio Total - Armazém", correios: false, categoria: "extravio" },
  { codigo: "24", descricao: "Cancelamento de lista", correios: false, categoria: "cancelado" },
  { codigo: "26", descricao: "Cancelamento de status finalizador", correios: false, categoria: "cancelado" },
  { codigo: "28", descricao: "Excluída da lista", correios: false, categoria: "cancelado" },
  { codigo: "32", descricao: "Falta no recebimento de transferência", correios: false, categoria: "extravio" },
  { codigo: "36", descricao: "Devolução em Rota", correios: false, categoria: "devolucao" },
  { codigo: "39", descricao: "Ocorrência", correios: false, categoria: "outro" },
  { codigo: "43", descricao: "Recebido no CD Coletado", correios: false, categoria: "coleta" },
  { codigo: "45", descricao: "Suspeita de extravio", correios: false, categoria: "extravio" },
  { codigo: "46", descricao: "A caminho do destinatário", correios: false, categoria: "em_transito" },
  { codigo: "48", descricao: "Recebido no CD Parcial", correios: false, categoria: "em_transito" },
  { codigo: "54", descricao: "Avaria Parcial - Armazém", correios: false, categoria: "avaria" },
  { codigo: "55", descricao: "Avaria Parcial - Motorista", correios: false, categoria: "avaria" },
  { codigo: "56", descricao: "Avaria Total - Armazém", correios: false, categoria: "avaria" },
  { codigo: "57", descricao: "Avaria Total - Motorista", correios: false, categoria: "avaria" },
  { codigo: "59", descricao: "Recoletar", correios: false, categoria: "coleta" },
  { codigo: "61", descricao: "Agendado", correios: false, categoria: "agendamento" },
  { codigo: "63", descricao: "Extravio Total - Motorista", correios: false, categoria: "extravio" },
  { codigo: "65", descricao: "Transferência de lista", correios: false, categoria: "transferencia" },
  { codigo: "67", descricao: "Coleta finalizada por limite máximo de tratativas", correios: false, categoria: "coleta" },
  { codigo: "69", descricao: "Salvados", correios: false, categoria: "extravio" },
  { codigo: "71", descricao: "Sinistro Aguardando Seguradora", correios: false, categoria: "extravio" },
  { codigo: "73", descricao: "Sinistro Solucionado", correios: false, categoria: "extravio" },
  { codigo: "109", descricao: "Coleta Recusada pela Operação - Divergência", correios: false, categoria: "insucesso" },
  { codigo: "110", descricao: "Coleta Devolvida ao Consumidor", correios: false, categoria: "coleta" },
  { codigo: "111", descricao: "Coleta Finalizada - Erro Motorista", correios: false, categoria: "coleta" },
  { codigo: "112", descricao: "Coleta Finalizada - Erro Base", correios: false, categoria: "coleta" },
  { codigo: "113", descricao: "Aguardando liberação pelo embarcador", correios: false, categoria: "em_transito" },
  { codigo: "115", descricao: "Calendarizado", correios: false, categoria: "agendamento" },
  { codigo: "117", descricao: "Coleta Recebida após Divergência", correios: false, categoria: "coleta" },
  { codigo: "119", descricao: "Tratado automaticamente pelo App", correios: false, categoria: "em_transito" },
  { codigo: "121", descricao: "Solicitação recebida pela transportadora", correios: false, categoria: "em_transito" },
  { codigo: "125", descricao: "CT-e autorizado", correios: false, categoria: "fiscal" },
  { codigo: "128", descricao: "Aguardando Agendamento", correios: false, categoria: "agendamento" },
  { codigo: "132", descricao: "Insucesso no Agendamento", correios: false, categoria: "insucesso" },
  { codigo: "135", descricao: "Aguardando integração", correios: false, categoria: "em_transito" },
  { codigo: "136", descricao: "Encomenda Não Integrada", correios: false, categoria: "outro" },
  { codigo: "238", descricao: "Avaria aguardando análise de cobrança", correios: false, categoria: "avaria" },
  { codigo: "317", descricao: "Ressarcimento em Tratativa", correios: false, categoria: "em_transito" },
  { codigo: "318", descricao: "Ressarcimento Pago", correios: false, categoria: "em_transito" },
  { codigo: "332", descricao: "Geração de lista de integração", correios: false, categoria: "em_transito" },
  { codigo: "372", descricao: "Consolidada", correios: false, categoria: "em_transito" },
  { codigo: "373", descricao: "Desconsolidada", correios: false, categoria: "em_transito" },
  { codigo: "376", descricao: "Falta na desconsolidação", correios: false, categoria: "extravio" },
  { codigo: "379", descricao: "Consolidação cancelada", correios: false, categoria: "cancelado" },
  { codigo: "441", descricao: "Em Análise de Indenização", correios: false, categoria: "em_transito" },
  { codigo: "442", descricao: "Tratativa de Indenização", correios: false, categoria: "outro" },
  { codigo: "443", descricao: "Ressarcimento Negado", correios: false, categoria: "em_transito" },
  { codigo: "454", descricao: "Solicitação Baixa Interna", correios: false, categoria: "outro" },
  { codigo: "458", descricao: "Baixa Interna Negada", correios: false, categoria: "outro" },
  { codigo: "462", descricao: "Baixada Internamente", correios: false, categoria: "outro" },
  { codigo: "476", descricao: "Em Transferência com Ocorrência", correios: false, categoria: "transferencia" },
  { codigo: "488", descricao: "Recebimento de Devolução", correios: false, categoria: "devolucao" },
  { codigo: "489", descricao: "Falta no Recebimento de Devolução", correios: false, categoria: "extravio" },
  { codigo: "493", descricao: "Aguardando tratativa/analise para devolução", correios: false, categoria: "devolucao" },
  { codigo: "516", descricao: "Sinistro não solucionado", correios: false, categoria: "extravio" },
  { codigo: "538", descricao: "Devolvido em Loja", correios: false, categoria: "devolucao" },
  { codigo: "161", descricao: "Avaria no Transporte", correios: false, categoria: "avaria" },
  { codigo: "162", descricao: "Material não Localizado", correios: false, categoria: "extravio" },
  { codigo: "163", descricao: "Material não Disponivel", correios: false, categoria: "outro" },
  { codigo: "164", descricao: "Coletado por Outra Transportadora", correios: false, categoria: "coleta" },
  { codigo: "165", descricao: "Venda Cancelada", correios: false, categoria: "cancelado" },
  { codigo: "166", descricao: "Local Fechado", correios: false, categoria: "outro" },
  { codigo: "167", descricao: "Cliente descartou/doou o produto", correios: false, categoria: "outro" },
  { codigo: "168", descricao: "Cliente mudou de endereço", correios: false, categoria: "outro" },
  { codigo: "169", descricao: "Coleta Cancelada - Cliente desistiu", correios: false, categoria: "cancelado" },
  { codigo: "170", descricao: "Coleta Recusada - aguarda estorno ou entrega de novo item", correios: false, categoria: "insucesso" },
  { codigo: "171", descricao: "Coleta Recusada - Cliente não reconhece a coleta", correios: false, categoria: "insucesso" },
  { codigo: "172", descricao: "Coleta Recusada - cliente se recusa a devolver", correios: false, categoria: "insucesso" },
  { codigo: "173", descricao: "Condomínio com restrição de horário", correios: false, categoria: "outro" },
  { codigo: "174", descricao: "Divergência na Quantidade de Volumes", correios: false, categoria: "outro" },
  { codigo: "175", descricao: "Endereço não localizado", correios: false, categoria: "extravio" },
  { codigo: "176", descricao: "Produto Montado/Desembalado", correios: false, categoria: "outro" },
  { codigo: "177", descricao: "Area de Risco", correios: false, categoria: "insucesso" },
  { codigo: "178", descricao: "Cliente ausente", correios: false, categoria: "insucesso" },
  { codigo: "179", descricao: "Aguardando posicionamento Embarcador", correios: false, categoria: "em_transito" },
  { codigo: "180", descricao: "Falta no recebimento de transferência", correios: false, categoria: "extravio" },
  { codigo: "181", descricao: "Coleta prejudicada pelo horário", correios: false, categoria: "coleta" },
  { codigo: "182", descricao: "Coleta cancelada pelo SAC", correios: false, categoria: "cancelado" },
  { codigo: "183", descricao: "Produto em outro endereço", correios: false, categoria: "outro" },
  { codigo: "184", descricao: "Não Visitado", correios: false, categoria: "outro" },
  { codigo: "185", descricao: "Baú cheio", correios: false, categoria: "outro" },
  { codigo: "189", descricao: "Cliente Ausente 1a Tentativa", correios: false, categoria: "insucesso" },
  { codigo: "190", descricao: "Cliente Ausente 2a Tentativa", correios: false, categoria: "insucesso" },
  { codigo: "191", descricao: "Cliente Ausente 3a Tentativa", correios: false, categoria: "insucesso" },
  { codigo: "193", descricao: "Produto recusado na devolução pelo embarcador", correios: false, categoria: "insucesso" },
  { codigo: "198", descricao: "Problemas com a fiscalização", correios: false, categoria: "outro" },
  { codigo: "199", descricao: "Feriado nacional", correios: false, categoria: "outro" },
  { codigo: "200", descricao: "Coleta não realizada por item divergente", correios: false, categoria: "insucesso" },
  { codigo: "201", descricao: "Coleta não realizada produto desembalado", correios: false, categoria: "insucesso" },
  { codigo: "202", descricao: "Praça de coleta não atendida pelo transportador", correios: false, categoria: "coleta" },
  { codigo: "203", descricao: "Roubo do item coletado", correios: false, categoria: "coleta" },
  { codigo: "204", descricao: "Problemas de endereço de coleta", correios: false, categoria: "coleta" },
  { codigo: "205", descricao: "Coleta recusada pelo cliente, aguarda troca casada", correios: false, categoria: "insucesso" },
  { codigo: "217", descricao: "Loja recusou processo de coleta", correios: false, categoria: "coleta" },
  { codigo: "218", descricao: "Loja fechada", correios: false, categoria: "outro" },
  { codigo: "220", descricao: "Cliente indisponível solicitou agendamento", correios: false, categoria: "agendamento" },
  { codigo: "222", descricao: "Greve / Manifestação / Paralisação", correios: false, categoria: "outro" },
  { codigo: "224", descricao: "Suspeita de extravio", correios: false, categoria: "extravio" },
  { codigo: "227", descricao: "Quebra de Veículo", correios: false, categoria: "outro" },
  { codigo: "355", descricao: "Cliente Desconhecido", correios: false, categoria: "insucesso" },
  { codigo: "358", descricao: "Coleta não efetuada - feriado local", correios: false, categoria: "insucesso" },
  { codigo: "351", descricao: "Epidemia - cliente solicitou reagendamento", correios: false, categoria: "agendamento" },
  { codigo: "402", descricao: "Local fechado para devolução", correios: false, categoria: "devolucao" },
  { codigo: "403", descricao: "Responsável pela devolução ausente", correios: false, categoria: "insucesso" },
  { codigo: "483", descricao: "Interdição de rodovia/estrada", correios: false, categoria: "outro" },
  { codigo: "541", descricao: "A entrega do objeto está condicionada à composição do lote", correios: true, categoria: "insucesso" },
  { codigo: "542", descricao: "A entrega não pode ser efetuada", correios: true, categoria: "insucesso" },
  { codigo: "543", descricao: "A entrega não pode ser efetuada - Carteiro não atendido", correios: true, categoria: "insucesso" },
  { codigo: "544", descricao: "A entrega não pode ser efetuada - Cliente desconhecido no local", correios: true, categoria: "insucesso" },
  { codigo: "545", descricao: "A entrega não pode ser efetuada - Cliente mudou-se", correios: true, categoria: "insucesso" },
  { codigo: "546", descricao: "A entrega não pode ser efetuada - Cliente recusou- se a receber", correios: true, categoria: "insucesso" },
  { codigo: "547", descricao: "A entrega não pode ser efetuada - Destinatário não apresentou documento exigido", correios: true, categoria: "insucesso" },
  { codigo: "548", descricao: "A entrega não pode ser efetuada - Empresa sem expediente", correios: true, categoria: "insucesso" },
  { codigo: "549", descricao: "A entrega não pode ser efetuada - Endereço incorreto", correios: true, categoria: "insucesso" },
  { codigo: "550", descricao: "A entrega não pode ser efetuada - Logradouro com numeração irregular", correios: true, categoria: "insucesso" },
  { codigo: "551", descricao: "A importação do objeto/conteúdo não foi autorizada pelos órgãos fiscalizadores", correios: true, categoria: "outro" },
  { codigo: "552", descricao: "Área com distribuição sujeita a prazo diferenciado", correios: true, categoria: "outro" },
  { codigo: "553", descricao: "As dimensões do objeto impossibilitam o tratamento e a entrega", correios: true, categoria: "insucesso" },
  { codigo: "554", descricao: "Coleta ou entrega de objeto não efetuada", correios: true, categoria: "insucesso" },
  { codigo: "555", descricao: "Declaração aduaneira ausente ou incorreta", correios: true, categoria: "insucesso" },
  { codigo: "556", descricao: "Destinatário não retirou objeto na Unidade dos Correios", correios: true, categoria: "insucesso" },
  { codigo: "557", descricao: "Entrega de objeto bloqueada a pedido do remetente", correios: true, categoria: "insucesso" },
  { codigo: "558", descricao: "Favor desconsiderar a informação anterior", correios: true, categoria: "outro" },
  { codigo: "559", descricao: "Lote de objetos incompleto", correios: true, categoria: "insucesso" },
  { codigo: "560", descricao: "Objeto aguardando retirada no endereço indicado", correios: true, categoria: "insucesso" },
  { codigo: "561", descricao: "Objeto apreendido por órgão de fiscalização ou outro órgão anuente", correios: true, categoria: "insucesso" },
  { codigo: "562", descricao: "Objeto coletado", correios: true, categoria: "coleta" },
  { codigo: "563", descricao: "Objeto com atraso na entrega", correios: true, categoria: "outro" },
  { codigo: "564", descricao: "Objeto com data de entrega agendada", correios: true, categoria: "agendamento" },
  { codigo: "565", descricao: "Objeto devolvido ao remetente", correios: true, categoria: "devolucao" },
  { codigo: "566", descricao: "Objeto devolvido aos Correios", correios: true, categoria: "devolucao" },
  { codigo: "567", descricao: "Objeto disponível para retirada em Caixa Postal", correios: true, categoria: "outro" },
  { codigo: "568", descricao: "Objeto e/ou conteúdo avariado", correios: true, categoria: "avaria" },
  { codigo: "569", descricao: "Objeto e/ou conteúdo avariado por acidente com veículo", correios: true, categoria: "avaria" },
  { codigo: "570", descricao: "Objeto encaminhado para", correios: true, categoria: "em_transito" },
  { codigo: "571", descricao: "Objeto endereçado à empresa falida", correios: true, categoria: "insucesso" },
  { codigo: "572", descricao: "Objeto entregue ao destinatário", correios: true, categoria: "entregue" },
  { codigo: "573", descricao: "Objeto Extraviado", correios: true, categoria: "extravio" },
  { codigo: "574", descricao: "Objeto liberado pela alfândega", correios: true, categoria: "em_transito" },
  { codigo: "575", descricao: "Objeto mal encaminhado", correios: true, categoria: "em_transito" },
  { codigo: "576", descricao: "Objeto não localizado", correios: true, categoria: "extravio" },
  { codigo: "577", descricao: "Objeto postado", correios: true, categoria: "em_transito" },
  { codigo: "578", descricao: "Objeto postado após o horário limite da agência", correios: true, categoria: "em_transito" },
  { codigo: "579", descricao: "Objeto recebido em", correios: true, categoria: "em_transito" },
  { codigo: "580", descricao: "Objeto recebido na unidade de distribuição", correios: true, categoria: "em_transito" },
  { codigo: "581", descricao: "Objeto recebido na unidade de exportação", correios: true, categoria: "em_transito" },
  { codigo: "582", descricao: "Objeto recebido na Unidade dos Correios", correios: true, categoria: "em_transito" },
  { codigo: "583", descricao: "Objeto recebido no Brasil", correios: true, categoria: "em_transito" },
  { codigo: "584", descricao: "Objeto reimpresso e reenviado", correios: true, categoria: "em_transito" },
  { codigo: "585", descricao: "Objeto roubado", correios: true, categoria: "extravio" },
  { codigo: "586", descricao: "Objeto saiu para entrega ao destinatário", correios: true, categoria: "em_transito" },
  { codigo: "587", descricao: "Objeto saiu para entrega ao remetente", correios: true, categoria: "em_transito" },
  { codigo: "588", descricao: "Objeto será devolvido por solicitação do remetente", correios: true, categoria: "devolucao" },
  { codigo: "589", descricao: "Para recebimento do objeto, é necessário o pagamento do ICMS Importação", correios: true, categoria: "outro" },
  { codigo: "590", descricao: "Remetente não retirou objeto na Unidade dos Correios", correios: true, categoria: "insucesso" },
  { codigo: "591", descricao: "Retirada em Unidade dos Correios não autorizada pelo remetente", correios: true, categoria: "insucesso" },
  { codigo: "592", descricao: "Revisão de tributo concluída - Objeto liberado", correios: true, categoria: "em_transito" },
  { codigo: "593", descricao: "Revisão de tributo concluída - Tributo alterado", correios: true, categoria: "outro" },
  { codigo: "594", descricao: "Revisão de tributo concluída - Tributo mantido", correios: true, categoria: "outro" },
  { codigo: "595", descricao: "Saída para entrega cancelada", correios: true, categoria: "insucesso" },
  { codigo: "596", descricao: "Solicitada revisão do tributo estabelecido", correios: true, categoria: "outro" },
  { codigo: "597", descricao: "Tentativa de entrega não efetuada", correios: true, categoria: "insucesso" },
]);
